### ISSUE TITLE
Can't Access to Recovery Anymore via Power + Vol UP

### ISSUE THREAD

**Issue by evansourav** [zwliew/android_device_xiaomi_hm2014811#121]
Can't Access to Recovery Anymore via Power + Vol UP,It Stops on Mi Logo,Flashing fastboot ROM Helps But then again anything that has been flashed via recovery doesn't.
ROM is close to Perfect,Keep your Good work Up Buddy

**Comment by aldi45ckr** [comment]
Power + volume up + volume down

**Comment by akashiyu** [comment]
This is because default developer mode is disabled. Goto About phone in
settings and click on build number for 5-7 times.
On 03-Oct-2015 3:52 pm, "aldi45ckr" <notifications@github.com> wrote:

Power + volume up + volume down

—
Reply to this email directly or view it on GitHub
<https://github.com/zwliew/android_device_xiaomi_hm2014811/issues/121#issuecomment-145235322>
.

**Comment by zwliew** [comment]
As @aldi45ckr has said, Power + volume up + volume down.
