### ISSUE TITLE
Z ram

### ISSUE THREAD

**Issue by devilgoldy** [zwliew/android_device_xiaomi_hm2014811#44]
Can you completely disabled z ram on last build or decrease z ram size because I use z ram for high graphics game

**Comment by zwliew** [comment]
Disabled in next build.

**Comment by devilgoldy** [comment]
Why you disable zram 1gb ram is not enough for redmi 2 normal game like dead trigger 1 crash on high graphics setting  but when zram on dead trigger runs smoothly 
I say  not disable z ram if you want disable z ram decrease the size to zero if any user use zram  user increase the size

**Comment by zwliew** [comment]
Sorry, your issue message was saying to disable zRAM. I'm still looking into zRAM as it is a really suckish solution to low RAM on Android.

**Comment by zwliew** [comment]
Anyway zram was already enabled in the previous build, so what was this issue for?

**Comment by balika011** [comment]
We need the fuck'n zram. At least 256MB.

**Comment by zwliew** [comment]
From my testing, zRAM barely even reached 100 MB of compressed cache after about a week. That includes opening basically all of my installed apps. Furthermore, zRAM causes quite a significant increase in CPU usage and load average.

As I said before, I'm still looking into it to recognize its benefits. No need for aggressive comments.

**Comment by zwliew** [comment]
Oh and one last thing, Dead Trigger runs smoothly (60fps with some frame drops here and there) even without zRAM. It wouldn't make much sense if it didn't.

**Comment by kb0n** [comment]
zRAM only makes sense for keeping more apps "alive" (or resumable), not necessarily for perfomance of the active app.
In general, the less zRAM you have, the more uncompressed "actual" RAM you have, the less CPU consumtion you have for (de-)compression from/into zRAM => overall better performance. Of course this only holds if memory management allows freeing RAM of inactive apps, otherwise those inactive apps would better be in zRAM to occupy less memory.
So it's rather a matter of RAM management. Plain statements like "just disable it" or "we need the fkn zram" are in the same sense meaningless.

@zwilew Have you looked into using swap partitions?

**Comment by zwliew** [comment]
@kb0n you pretty much just explained why I said "It wouldn't make sense if it (the game) didn't (run smoothly)." 

@balika011 @devilgoldy Ifreally want zRAM, just download Kernel Adiutor and enable it yourself. I won't enable zRAM by default until I find a compelling reason to do so in my usage.
